// student_info
#include <stdio.h>
typedef struct  student_info {
    char name[50];
    char address[60];
    // we cant make bit_feild on char because cant use with array of pointer
    int age:8;
    float marks:3;
}s;

int main() {
    int c=0 ;
    printf("the size of struct is%d",sizeof(s));
    s s1= {"eman","zagazig",21,16} ;
    printf("student {1}:\n");
    printf("Name:%s\n", s1.name);
    printf("address :%s\n", s1.address);
    printf("age: %d\n", s1.age);
    printf("Marks: %.1f\n", s1.marks);
    printf("-----------------\n");
    s s2= {"noha","zagazig",21,20} ;
    printf("student {2}:\n");
    printf("Name:%s\n", s2.name);
    printf("address :%s\n", s2.address);
    printf("age: %d\n", s2.age);
    printf("Marks: %.1f\n", s2.marks);
    printf("-----------------\n");
    s s3= {"mona","zagazig",21,12} ;
    printf("student {3}:\n");
    printf("Name:%s\n", s3.name);
    printf("address :%s\n", s3.address);
    printf("age: %d\n", s3.age);
    printf("Marks: %.1f\n", s3.marks);
    printf("-----------------\n");
    s s4= {"ahmed","zagazig",21,11} ;
    printf("student {4}:\n");
    printf("Name:%s\n", s4.name);
    printf("address :%s\n", s4.address);
    printf("age: %d\n", s4.age);
    printf("Marks: %.1f\n", s4.marks);
    printf("-----------------\n");
    s s5= {"reham","zagazig",21,10} ;
    printf("student {5}:\n");
    printf("Name:%s\n", s5.name);
    printf("address :%s\n", s5.address);
    printf("age: %d\n", s5.age);
    printf("Marks: %.1f\n", s5.marks);
    printf("-----------------\n");
    s s6= {"ali","zagazig",21,9} ;
    printf("student {6}:\n");
    printf("Name:%s\n", s6.name);
    printf("address :%s\n", s6.address);
    printf("age: %d\n", s6.age);
    printf("Marks: %.1f\n", s6.marks);
    printf("-----------------\n");
    s s7= {"mohamed","zagazig",21,8} ;
    printf("student {7}:\n");
    printf("Name:%s\n", s7.name);
    printf("address :%s\n", s7.address);
    printf("age: %d\n", s7.age);
    printf("Marks: %.1f\n", s7.marks);
    printf("-----------------\n");
    s s8= {"salma","zagazig",21,16} ;
    printf("student {8}:\n");
    printf("Name:%s\n", s8.name);
    printf("address :%s\n", s8.address);
    printf("age: %d\n", s8.age);
    printf("Marks: %.1f\n", s8.marks);
    printf("-----------------\n");
    s s9= {"soha","zagazig",21,20} ;
    printf("student {9}:\n");
    printf("Name:%s\n", s9.name);
    printf("address :%s\n", s9.address);
    printf("age: %d\n", s9.age);
    printf("Marks: %.1f\n", s9.marks);
    printf("-----------------\n");
    s s10= {"shimaa","zagazig",21,18} ;
    printf("student {10}:\n");
    printf("Name:%s\n", s10.name);
    printf("address :%s\n", s10.address);
    printf("age: %d\n", s10.age);
    printf("Marks: %.1f\n", s10.marks);
    printf("-----------------\n");
    s s11= {"esraa","zagazig",21,19} ;
    printf("student {11}:\n");
    printf("Name:%s\n", s11.name);
    printf("address :%s\n", s11.address);
    printf("age: %d\n", s11.age);
    printf("Marks: %.1f\n", s1.marks);
    printf("-----------------\n");
    s s12= {"reem","zagazig",21,13} ;
    printf("student {12}:\n");
    printf("Name:%s\n", s12.name);
    printf("address :%s\n", s12.address);
    printf("age: %d\n", s12.age);
    printf("Marks: %.1f\n", s12.marks);
    printf("-----------------\n");
    s s13= {"toka","zagazig",21,17} ;
    printf("student {13}:\n");
    printf("Name:%s\n", s13.name);
    printf("address :%s\n", s1.address);
    printf("age: %d\n", s13.age);
    printf("Marks: %.1f\n", s13.marks);
    printf("-----------------\n");
    s s14= {"sleem","zagazig",21,17} ;
    printf("student {14}:\n");
    printf("Name:%s\n", s14.name);
    printf("address :%s\n", s14.address);
    printf("age: %d\n", s14.age);
    printf("Marks: %.1f\n", s14.marks);
    printf("-----------------\n");
    s s15= {"hazem","zagazig",21,16} ;
    printf("student {15}:\n");
    printf("Name:%s\n", s15.name);
    printf("address :%s\n", s15.address);
    printf("age: %d\n", s15.age);
    printf("Marks: %.1f\n", s15.marks);
    printf("-----------------\n");
    
    return 0;
}

